[profile.dev]
overflow-checks = false # https://doc.rust-lang.org/cargo/reference/profiles.html


[workspace]
members = [
    "exercises/*/*",
    "helpers/common",
    "helpers/mdbook-exercise-linker",
    "helpers/ticket_fields",
]
resolver = "2"
